# Default values for faros-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api:
  replicaCount: 1
  image:
    repository: ghcr.io/faroshq/faros-ingress/api
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

gateway:
  replicaCount: 1
  image:
    repository: ghcr.io/faroshq/faros-ingress/gateway
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

cloudflare:
  key: ""
  email: ""

database:
  name: faros
  user: faros
  password: farosfaros

certificates:
  useStaging: false
  privateKeys:
    algorithm: RSA
    size: 2048
  subject: {}

ingress:
  enabled: false
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
  hosts:
    - host: api.faros.sh
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
  - secretName: faros-cert
    hosts:
      - api.faros.sh
