apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    {{- include "faros-dev.labels" . | nindent 4 }}
  name: faros-ingestor
  namespace: faros
spec:
  rules:
  - host: '*.apps.dev.faros.sh'
    http:
      paths:
      - backend:
          service:
            name: faros-gateway
            port:
              number: 8444
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - "*.apps.dev.faros.sh"
    secretName: faros-ingestor
