---
apiVersion: v1
kind: Service
metadata:
  name: faros-gateway-node
  labels:
    app.kubernetes.io/name: faros-gateway
spec:
  type: NodePort
  ports:
    - port: 8444
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30444
  selector:
    app.kubernetes.io/name: faros-gateway
