---
apiVersion: v1
kind: Service
metadata:
  name: faros-gateway
  labels:
    app.kubernetes.io/name: faros-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8444
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: faros-gateway
