---
apiVersion: v1
kind: Service
metadata:
  name: faros-api-node
  labels:
    app.kubernetes.io/name: faros-api
spec:
  type: NodePort
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30443
  selector:
    app.kubernetes.io/name: faros-api
