apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: faros-api-secret-reader
  namespace: dex
subjects:
- kind: ServiceAccount
  name: faros-api
  namespace: faros
roleRef:
  kind: ClusterRole
  name: faros-api-secret-reader
  apiGroup: rbac.authorization.k8s.io
