apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.database.name }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:10.1
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql
              name: postgredb
            - mountPath: /docker-entrypoint-initdb.d
              name: postgresql-initdb
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: {{ .Values.database.name }}-db-storage
        - name: postgresql-initdb
          configMap:
            name: postgresql-initdb-config
