---
apiVersion: v1
kind: Service
metadata:
  name: faros-api-ext
  labels:
    app.kubernetes.io/name: faros-api
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: faros-api
---
apiVersion: v1
kind: Service
metadata:
  name: faros-api
  labels:
    app.kubernetes.io/name: faros-api
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: https
      protocol: TCP
      name: https
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: faros-api
