---
apiVersion: v1
kind: Service
metadata:
  name: faros-gateway-ext
  labels:
    app.kubernetes.io/name: faros-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: faros-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: faros-gateway
  labels:
    app.kubernetes.io/name: faros-gateway
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: faros-gateway
