kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
featureGates:
  EphemeralContainers: true
name: faros
nodes:
  - role: control-plane
    image: kindest/node:v1.24.0
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 443
        hostPort: 443
        protocol: TCP
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      # faros api port
      - containerPort: 30443
        hostPort: 30443
        protocol: TCP
      # faros gateway port
      - containerPort: 30444
        hostPort: 30444
        protocol: TCP
      # faros ingestor port
      - containerPort: 30445
        hostPort: 30445
        protocol: TCP
