# Default values for faros-dev.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

api:
  replicaCount: 1
  image:
    repository: ghcr.io/faroshq/faros-ingress/reverse-proxy
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

gateway:
  replicaCount: 1
  image:
    repository: ghcr.io/faroshq/faros-ingress/reverse-proxy
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

certificates:
  privateKeys:
    algorithm: RSA
    size: 2048
  subject: {}

ingress:
  enabled: false
  className: "nginx"
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
  hosts:
    - host: faros-dev.dev.faros.sh
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: {}
  #  - secretName: faros-cert
  #    hosts:
  #      - faros-dev.dev.faros.sh
  #      - faros
  #      - localhost
